### ISSUE TITLE
updateSelectedKey is outdated

### ISSUE THREAD

**Issue by stefanuebe** [vaadin-component-factory/combo-box-light#2]
With V24 it seems like the combobox has no "_selectedKey" anymore, but uses the "value" property instead to define, which item should be shown as selected. 

Therefore updateSelectedKey should set the "value" property with the up-to-date keymapper key to prevent the client side to "forget" the selected value, when updating the items.

Sample to reproduce the issue is to set the item label generator after the value has been set. 

```java
var light = new ComboBoxLight<SamplePerson>();
light.setItems(LIST);
light.setValue(LIST.get(0));
light.setItemLabelGenerator(SamplePerson::getName);
add(light);
```

**Comment by TatuLund** [comment]
Fixed in version 2.0.0
