### ISSUE TITLE
Align setValue behavior to the normal combobox

### ISSUE THREAD

**Issue by stefanuebe** [vaadin-component-factory/combo-box-light#3]
In V24, the core ComboBox (and other similar components) allow to set a value even if it is not part of the items. Despite the pros and cons regarding that behaviour, the CBL should behave the same and allow the same (as long as the CB does), to assure a uniform behaviour of "selector" components.

Therefore the methods `modelToPresentation` and `presentationToModel` should be reimplemented as they are in the core CB.

**Comment by TatuLund** [comment]
Fixed in version 2.0.0
