### ISSUE TITLE
Accessing the data provider before setting it leads to a NPE (internal issue)

### ISSUE THREAD

**Issue by stefanuebe** [vaadin-component-factory/combo-box-light#4]
The CBL does not initialize an empty data provider internally at construction time. This leads to a NullPointerException when any process calls reset() or access the data provider in any way without a proper null check. 

Currently appearing when setting the ItemLabelGenerator or using a custom renderer, without setting any items prior.

**Comment by TatuLund** [comment]
Fixed in version 2.0.0
